name: finatmo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - .env
